version: '3.8'

services:
  frontend:
    image: miki-demo-fronted
    build: ./miki-demo-frontend-trying
    networks:
      - app-network

  backend:
    image: miki-demo-api
    build: ./miki-demo-api
    ports:
      - "5000:5000" # Expose backend port for internal communication
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"   # Expose port 80 to access the application
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
