# Use the official NGINX image
FROM nginx:stable-perl

# Copy the custom NGINX configuration file into the container
COPY ./default.conf /etc/nginx/default.conf

# Expose port 80 to the outside world
EXPOSE 80